# Generated by Django 4.1.4 on 2023-04-05 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="tweet_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
