# Generated by Django 4.1.4 on 2023-05-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_tweet_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="homepage_link",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_link",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_link",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_bio",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
