# Generated by Django 4.1.4 on 2023-05-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_profile_homepage_link_profile_instagram_link_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweet",
            options={"ordering": ["-created_at"]},
        ),
    ]
