# Generated by Django 4.1.4 on 2023-05-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_tweet_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="body",
            field=models.CharField(max_length=500),
        ),
    ]
