# Generated by Django 4.1.4 on 2023-04-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="booker_data",
            field=models.CharField(help_text="Name and Surname", max_length=200),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="cancellation_date",
            field=models.BooleanField(default=False, help_text="Cancel your event"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time",
            field=models.TimeField(),
        ),
    ]
