# Generated by Django 4.1.4 on 2023-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_alter_calendarevent_booker_data_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ("-day", "start_time"),
                "verbose_name": "Event",
                "verbose_name_plural": "Scheduling",
            },
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time",
            field=models.DateTimeField(),
        ),
    ]
