# Generated by Django 4.1.4 on 2023-04-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_alter_event_options_alter_calendarevent_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarevent",
            name="date",
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="start_time",
            field=models.DateTimeField(help_text="Starting time"),
        ),
    ]
