# Generated by Django 4.1.4 on 2023-05-03 19:48

import datetime
from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_remove_calendarevent_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=500)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time",
            field=reservation.models.CustomDateTimeField(
                default=datetime.datetime(2023, 5, 3, 22, 48, 53, 366719),
                help_text="Final time",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 3, 21, 48, 53, 366718),
                help_text="Starting time",
            ),
        ),
    ]
