# Generated by Django 4.1.4 on 2023-05-16 11:52

import datetime
from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0005_calendar_alter_calendarevent_end_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calendarevent",
            old_name="cancellation_date",
            new_name="cancel_event",
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time",
            field=reservation.models.CustomDateTimeField(
                default=datetime.datetime(2023, 5, 16, 14, 52, 7, 757969),
                help_text="Final time",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 16, 13, 52, 7, 757968),
                help_text="Starting time",
            ),
        ),
    ]
