# Generated by Django 4.1.4 on 2023-05-17 11:18

import datetime
from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0006_rename_cancellation_date_calendarevent_cancel_event_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Calendar",
            new_name="Events",
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="cancel_event",
            field=models.BooleanField(default=False, help_text="Cancel this event"),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time",
            field=reservation.models.CustomDateTimeField(
                default=datetime.datetime(2023, 5, 17, 14, 17, 33, 40159),
                help_text="Final time",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 17, 13, 17, 33, 40159),
                help_text="Starting time",
            ),
        ),
    ]
