# Generated by Django 4.1.4 on 2023-05-19 16:54

import datetime
from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_rename_calendar_events_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={
                "ordering": ("-start",),
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time",
            field=reservation.models.CustomDateTimeField(
                default=datetime.datetime(2023, 5, 19, 17, 54, 6, 660671),
                help_text="Final time",
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 19, 16, 54, 6, 660670),
                help_text="Starting time",
            ),
        ),
    ]
