# Generated by Django 4.1.4 on 2023-06-21 23:03

import datetime
from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0009_alter_calendarevent_end_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={
                "ordering": ("start",),
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="end_time",
            field=reservation.models.CustomDateTimeField(
                default=datetime.datetime.now, help_text="Final time"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="day",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
